apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configurations-dev
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  source:
    repoURL: https://github.com/mrislam11378/ace-demo-gitops.git
    targetRevision: main
    path: envs/dev/configurationCRs
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
